name: ts_course

channels:
  - conda-forge
dependencies:
  - python
  - altair
  - arviz
  - blackjax
  - ipykernel
  - ipython
  - ipywidgets
  - jax
  - jupyter_bokeh
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - numba
  - numpyro
  - nutpie
  - pandas
  - patsy
  - pip
  - plotly
  - polars
  - preliz
  - pyarrow
  - pymc
  - pydot
  - python-graphviz
  - pytensor
  - scipy
  - seaborn
  - setuptools
  - statsmodels
  - watermark
  - xlrd